site_name: Krate
copyright: 'Copyright &copy; 2023 the original author or authors.'
repo_url: https://github.com/lpicanco/krate/
nav:
  - Home: README.md
  - Reference: api/index.html
theme:
  name: 'material'
  icon:
    logo: 'fontawesome/solid/magnifying-glass-chart'
  features:
    - navigation.tabs
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
